### PR TITLE
Fix staged installation and mac osx problems with float

### PR DESCRIPTION
**Pull request by snoweye**
FYI @dselivanov @wrathematics

### CODE REVIEW

**Comment by dselivanov** [comment]
Thanks a lot for PR. I was playing around yesterday, but still don't fully understand how to properly test it... 
Also as per Simon suggestion I was thinking to link to static library. Do you see any downside of linking to static library instead of using staged installation and shared library?

**Comment by wrathematics** [comment]
Static linking will make the rsparse package shared library larger, and it would make it impossible to dynamically swap out for a different blas library (i.e., you'd have to recompile float and rsparse if you switched your libRblas).

At this point, I think it might be worth petitioning R core to include the single precision symbols in libRlapack and libRblas.

**Comment by dselivanov** [comment]
@wrathematics do you mean include symbols from your reference implementation? as I remember there was a story about current libRblas where r-core patched 'a lot of things' (i think corner cases). Not sure if this will be easy...

**Comment by snoweye** [comment]
I don't know why I kept missing you two's messages... I supposed to get e-mails, when there is any updates, no?
- [Here](https://github.com/snoweye/pbdZMQ/blob/master/.travis.yml#L45-L65) has some that I test.
- These are actually two questions: 1) caused by staged installation and 2) Simon's mac osx binary.
- For 1), you need both float and rsparse have right loading locations in mac osx. Since R-3.6.0, someone add the staged installation for other purposes, I don't really like the idea, but we get his side effects. Some codes are added in the `tools/R/install.R` to check and overwrite the loading locations. `install.libs.R` in rsparse will do the work before the check.
- For 2), Simon used other location to installation and collect the binary. The binary can be installed at any locations by end users. So, the additional overwrite in `zzz.R` is then designed to do the work for the end users (you may need to check if the end users have `otool` and `install_name_tool` and if the locations needed to be overwrite first). The end users may need root permission to do the overwrite, but we may assume most case they have in mac osx.
- The tests in `pbdZMQ` tired to mimic the case 2).

**Comment by dselivanov** [comment]
@snoweye with new rsparse 0.3.3.3 on CRAN the issue remains. @wrathematics  need to update float on CRAN?

> Error: package or namespace load failed for ‘rsparse’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rsparse/libs/rsparse.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rsparse/libs/rsparse.so, 6): Library not loaded: /Volumes/SSD-Data/Builds/R-dev-web/QA/Simon/packages/el-capitan-x86_64/Rlib/3.6/float/libs/float.so
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rsparse/libs/rsparse.so
  Reason: image not found

**Comment by wrathematics** [comment]
Oh, I thought you were going to switch to static linking. It seemed like Simon was sort of demanding that. I can try to merge the PR and update it (I never was able to even reproduce/fix a solaris issue, so they may reject it).

I'm not sure what they changed in libRblas/libRlapack. I suspect nothing of any substance, or they would have upstreamed the changes. I used to work down the hall from the LAPACK team, and I can tell you that I trust them more than I do R core for numerical computing. R core extensively modified the old Linpack code (predecessor to LAPACK, not the HPL benchmark), which is what drives linear models in R (`dqrls`).

The path of fewest headaches for you, me, and CRAN themselves would be to include single precision LAPACK/BLAS in R. We may not have reached a critical mass of annoyance for them yet though.

**Comment by dselivanov** [comment]
@wrathematics will you have a chance to release a new version of float in near future? If you are busy i will try to temporary switch to static linking.

**Pull request merged**
